config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index' 
  get 'persons/profile' 
 
  devise_for :users, controllers: {registrations: "registrations"}

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :tasks do 
    put :complete, :not_complete, on: :member
    get 'complete'
    get 'make_active'
    collection do
      post :destroy_multiple
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5, too_short: "%{count} characters is the minimum allowed"}

  def complete!
    self.completed = true
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  def full_name
    [first_name, last_name].join(' ')
  end

  def full_name=(name)
    elements = name.split(' ')
    self.last_name = elements.delete(elements.last)
    self.first_name = elements.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    
  def profile
  def after_sign_in_path_for(resource)
    current_user_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
  end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_in_params
    params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation)
  end

  def account_update_params
   params.require(:user).permit(:first_name,:last_name,:email,:password,:password_confirmation, :current_password)
  end
end

app/controllers/sessionscontroller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      if user.email_confirmed
        sing_in user
        redirect_back_or user
      else
        flash.now[:error] = 'Please activate your account by following the instructions in the account
        confirmation email you received to proceed'
        render 'new'
      end
    else
      flash.now[:error] = 'Invalid email/password combination' 
      render 'new'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:edit, :show, :update, :destroy, :complete, :not_complete]
  before_action :set_tasks, only: [:index, :complete, :make_active, :destroy]

  def index
  end

  def new
    @task = current_user.tasks.build()
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update_attributes task_params
    redirect_to tasks_path
  end

  def make_active
    if @task.update_attribute :completed, false
    end
  end

  def complete
    @task.complete!
    redirect_to tasks_path
  end

  def not_complete
    @task.update_attribute :completed, false
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def destroy_multiple
    current_user.tasks.where(id: params[:tasks]).destroy_all
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :priority, :completed, :due_date, :description, :user_id)
  end

  def sort_column
    params[:sort] ||= "priority"
  end

  def set_tasks
    # binding.pry
    @tasks = current_user.tasks.where(completed: false).order(updated_at: :desc)
    @completed_tasks = current_user.tasks.where(completed: true)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = "Please confirm your email address to continue"
      redirect_to root_url
    else
      flash[:error] = "Oooooppss, someting went wrong!"
      render 'new'
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to my To Do List! Your email has been confirmed.
      Please sing in to continue."
      redirect_to signin_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header col-lg-4 col-md-3 col-sm-2">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
				<span class="sr-only">Открить навигацию</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="responsive-menu">
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
				<li class="nav-task">
					<%= link_to 'Tasks List', tasks_path %></li>
				<li class="nav-task">
					<%= link_to 'Create Tasks', new_task_path %></li>
				<li class="nav-task">
					<%= link_to 'Profile', persons_profile_path %></li>
				<li class="nav-task">
					<%= link_to 'Log out', destroy_user_session_path, :method =>:delete %></li>
				<% else %>
				<li class="nav-item">
					<%= link_to 'Log in', new_user_session_path %></li>
				<li class="nav-item">
					<%= link_to 'Sign in', new_user_registration_path %></li>
				<% end %></ul>
		</div>
	</div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo1</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <script src="sorttable.js"></script>
  </head>
    <body>
      <%= render 'layouts/header' %>
      <p class="notice">
        <%= notice %></p>
      <p class="alert">
        <%= alert %></p>
      <div class="container">
        <div class="row">
        <%= yield %></div>
      </div>
    </body>
</html>

app/views/persons/profile.html.erb
<h3 class="text-center">Profile</h3>

<br>
<br>

<div class="container container_edit">
  <div class="row">
    <div class="col-sm-2"></div>

    <div class="col-md-8">
      <h4>
        First Name:
        <%= current_user.first_name %></h4>
      <br>
      <h4>
        ID:
        <%= current_user.id %></h4>
      <br>
      <h4>
        Email:
        <%= current_user.email %></h4>
      <br>
      <h4>
        Registration time:
        <%= current_user.current_sign_in_at %></h4>
      <br></div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="col-md-6">
<%= simple_form_for @task do |f| %>
	<p>
		<%= f.input :title %></p>
	<p>
		<%= f.input :priority %></p>
	<p>
		<%= f.input :description %></p>
	<p>
		<%= f.date_field :due_date, :required =>true, :value => Date.today, :min => Date.today %></p>
	<p>
		<%= f.input :completed %></p>
	<p>
		<%= f.button :submit %></p>
<% end %></div>

app/views/tasks/_task.html.erb
<tr class="hover1">
  <div  class="hover1">
    <div class="task priority_<%= task.priority  %> completed_<%= task.completed %>  ">
      <th>
        <%= check_box_tag 'tasks[]', task.id, false, class: 'batch-del batch-del-checkbox' %></th>

      <th class="title"  style="padding-left: 20px">
        <%= link_to task.title, task_path(task) %></th>
      <th class="title"  style="padding-left: 20px">
        <%= task.due_date %></th>
      <th class="title"  style="padding-left: 20px">
        <%= task.priority %></th>
      <th class="title"  style="padding-left: 20px">
        <%= task.description %></th>

      <th>
        <div class="hover2 pull-right" >
          <%= link_to content_tag('span', '', class: 'fa fa-pencil'), edit_task_path(task), class: 'action' %>
          <%= link_to content_tag('span', '', class: 'fa fa-trash'), task, method: :delete, class: 'action' %>
          <% unless task.completed? %>
          <%= link_to content_tag('span', '', class: 'fa fa-check-square-o'), complete_task_path(task), data: {method: :put}, class:'done action' %>
          <% else %>
          <%= link_to content_tag('span', '', class: 'fa fa-minus'), not_complete_task_path(task), data: {method: :put}, class:'done action' %>
        <% end %></div>
      </th>
    </div>
  </div>
</tr>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/completed_tasks.erb
<h3>Completed tasks</h3>
<%= form_tag destroy_multiple_tasks_path, class: 'completed_form' do %>
  <ul>
    <% @completed_tasks.each do |task| %>
      <%= link_to edit_task_path(task) do %>
        <li class="checkbox taskwrapper completedwrapper">
        <%= check_box_tag 'tasks[]', task.id %>
        <%= render partial: 'task', object: task %></li>
      <% end %>
    <% end %>
  </ul>
  <%= submit_tag "Delete selected", method: :delete, type: "submit", data: {confirm: "Are you sure?"}, class: "btn btn-danger batch-del-submit but_delete" %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="col-mb-12">
  <h1>Edit Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<%= link_to "Logout", destroy_user_session_path , method: :delete %>
<%= link_to "Edit profile", edit_user_registration_path %>

<div class="buffer-top">
  <%= link_to "New task", new_task_path, class: 'btn btn-primary' %></div>

  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <%= form_tag destroy_multiple_tasks_path  do  %>
        <ul>
          <table class="table pretty sortable table-bordered ">
            <thead>
              <tr>
                <div class="content">
                  <div class="row">
                    <th class="col-xs-1"></th>
                    <th class="col-xs-3">Title</th>
                    <th class="col-xs-1 text-center">Due Date</th>
                    <th class="col-xs-1 text-center">Priority</th>
                    <th class="col-xs-4">Deckription</th>
                    <th class="col-xs-2"></th>
                  </div>
                </div>
              </tr>
            </thead>
            <tbody>
              <% @tasks.each do |task| %>
              <li class="checkbox taskwrapper">
                <%= link_to edit_task_path(task) do %>
                <%= render partial: 'task', object: task %>
                <% end %>
              <% end %></li>
            </tbody>
          </table>
        </ul>
      </div>
    </div>
  </div>
  <%= submit_tag "Delete selected", method: :delete, type: "submit", data: { confirm: "Are you sure?" }, class: "btn btn-danger batch-del-submit but_delete"%>
<% end %>

<%= form_tag destroy_multiple_tasks_path  do  %>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <table class="table pretty sortable table-bordered ">
          <thead>
            <tr>
              <div class="content">
                <div class="row">
                  <th class="col-xs-1"></th>
                  <th class="col-xs-3">Title</th>
                  <th class="col-xs-1 text-center">Due Date</th>
                  <th class="col-xs-1 text-center">Priority</th>
                  <th class="col-xs-4">Deckription</th>
                  <th class="col-xs-2"></th>
                </div>
              </div>
            </tr>
          </thead>
          <tbody>
          <% @completed_tasks.each do |task| %>
          <%= render partial: 'task', object: task %>
          <% end %></tbody>
        </table>
      </div>
    </div>
  </div>
  <%= submit_tag "Delete selected", method: :delete, type: "submit", data: { confirm: "Are you sure?" }, class: "btn btn-danger batch-del-submit but_delete"%>
<% end %>

<input type="button" value="Check All" onclick="check();">
<input type="button" value="Uncheck All" onclick="uncheck();">

app/views/tasks/new.html.erb
  <div class="col-mb-12">
    <h1>New Task</h1>
  </div>
  <div class=" col-lg-4">
    <%= render 'form' %>
  </div>

app/views/tasks/show.html.erb
<h3 class="text-center">Tasks details</h3>
<br>
<br>
<div class="container container_edit">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-md-8">
      <h4>
        Title:
        <%= @task.title %></h4>
      <br>
      <h4>
        Description:
        <%= @task.description %></h4>
      <br>
      <h4>
        Date:
        <%= @task.due_date %></h4>
      <br>
      <h4>
        Priority:
        <%= @task.priority %></h4>
      <br>
    </div>
  </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>